pipeline
{
  agent { label 'New-Agent1'}

  stages {

    stage ('Build')
    { 
      steps{
          sh 'mvc clean package'
      }
      post {
        success {
            archiveArtifacts artifacts: '**/target/*.war'
                }
            }
    }


  }


}