pipeline
{
  agent { label 'New-Agent1'}

  stages {

    stage ('Build')
    { 
      steps{
          echo "This is build stage "
      }
    }

    stage ('Test') 
    {
      steps{
          echo "This is test stage"
      }
    }

    stage ('Deploy')
    {
      steps{
          echo "This is Deployment stage"
      }
    }




  }


}